### ISSUE TITLE
Update action syntax

### ISSUE THREAD

**Issue by budged** [maxsokolov/TableKit#22]
Hello, can you please add this method. I think this small update will really improve action chaining syntax.

You can add following method in TableRow class

```swift
public func action<T>(type: TableRowActionType, handler: (data: TableRowActionData<ItemType, CellType>) -> T) -> Self {
    actions[type.key] = TableRowAction(type, handler: handler)
    return self
 }
```

This will lead to much nicer syntax:
```swift
let row = TableRow<String, StringTableViewCell>(item: "some")
    .action(.click) { (data) in

    }
    .action(.shouldHighlight) { (data) -> Bool in
        return false
    }
```

**Comment by maxsokolov** [comment]
Hi @budged, 

That's definitely a good idea! I've made changes.
Thanks a lot for this clever improvement.

**Comment by maxsokolov** [comment]
Pod has been bumped to 0.8.2
