### ISSUE TITLE
Add support for sending custom actions from cells

### ISSUE THREAD

**Issue by zdenektopic** [maxsokolov/TableKit#25]
So we don't have to use delegate approach for cells.

Cell:
```
class StringTableViewCell: UITableViewCell, ConfigurableCell {

  @IBAction func sendTapped(sender: UIButton) {
    invokeCustomAction("send")
  }

}
```

Action in controller:
```
let action = TableRowAction<String, StringTableViewCell>(.custom("send")) { (data) in
  doSomeNetworking()
}
```

Maybe it is stupid idea, but seems reasonable to me.
Let me know what you think.

**Comment by zdenektopic** [comment]
Just found out it works just that way, nevermind :)

**Comment by maxsokolov** [comment]
Hi @zdenektopic 

Yeah) It's already supported. I have to add it to the docs and update an example.

**Comment by zdenektopic** [comment]
Also it would be great to add supporting method to ConfigurableCell so you don't have to create `TableCellAction` object yourself and call `invoke` on it every time.

**Comment by maxsokolov** [comment]
@zdenektopic good idea! I'll consider this improvement for a next release.

Thank you!

**Comment by maxsokolov** [comment]
btw, `userInfo` in `TableCellAction` is still in progress.
