### ISSUE TITLE
Table Sections - How to customize them?

### ISSUE THREAD

**Issue by andrealufino** [maxsokolov/TableKit#37]
Hi! Congratulations for the library, really cool and useful!
I need to create custom section cells, but the question is : how can I do it? I see the `TableSection` has a headerView property, but I'd like to know how can I customize the info inside my custom section cell and how can I reuse the section header cell.

**Comment by maxsokolov** [comment]
Hey, @andrealufino 

Thank you! 

If you are talking about [https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewHeaderFooterView_class/ ](this), then it's not yet supported.

But you are able to build headers for your sections like follows:
`
let header1 = UIView(frame: CGRectMake(0, 0, 100, 50))
header1.backgroundColor = UIColor.redColor()
        
let header2 = UIView(frame: CGRectMake(0, 0, 100, 50))
header2.backgroundColor = UIColor.greenColor()
        
let section1 = TableSection()
section1.headerView = header1
        
let section2 = TableSection()
section2.headerView = header2
`
You have to create a new header view for each section. You cannot actually reuse header view for now.

Or something like this:

`
func createHeaderView(color: UIColor) -> UIView {
        
    let header = UIView(frame: CGRectMake(0, 0, 100, 50))
    header.backgroundColor = color
        
    return header
}

let section1 = TableSection()
section1.headerView = createHeaderView(UIColor.greenColor())
        
let section2 = TableSection()
section2.headerView = createHeaderView(UIColor.redColor())
`

**Comment by andrealufino** [comment]
Ok, perfect! Clear!
Go on supporting this awesome library man, it's really cool!

**Comment by maxsokolov** [comment]
@andrealufino thanks! Yeah) I'm gonna improve and support it.
