### ISSUE TITLE
Row update and reorder animation

### ISSUE THREAD

**Issue by threat70** [maxsokolov/TableKit#43]
Hi, you created great way for work with UITableView, but I have some questions:
How update some data in row with animation?
How reorder row with animation?

Thanks

**Comment by maxsokolov** [comment]
Hi @threat70,
Sorry for late response.

**Comment by maxsokolov** [comment]
Hi @threat70,
Sorry for late response.

1) How update some data in row with animation?
You have to create a new row` let row = TableRow<String, StringTableViewCell>(item: "1")`, add it into `TableSection` or replace some row in `TableSection` at index and then just use regular UITableView methods to perform animations like `insertRowsAtIndexPaths`.

2) How reorder row with animation?
Just the same. Make changes in your `TableSection` and then use UITableView's methods to perform animations.

**Comment by threat70** [comment]
Thanks for the answer.
Do you will add functions for easy-to-use animation?

**Comment by maxsokolov** [comment]
@threat70 so it's actually possible, don't know when exactly, need to carefully think about this...
