### ISSUE TITLE
Improve Generic parameters

### ISSUE THREAD

**Issue by OdNairy** [maxsokolov/TableKit#45]
Hi there
In #42 where an interesting improvement by reusing `CellType.ItemType` generic. Would you add this one into repo? Can I help you with PR for that? May be @noxt want to make it first?

**Comment by maxsokolov** [comment]
Hi @OdNairy,

I'm personally really love this improvement. So it's all depends on my team's vision on this.

The case is that this `TableRow<String, StringTableViewCell>(item: "1")` is more informative than this `TableRow<StringTableViewCell>(item: "1")`. When you have really big and difficult tableviews with lots of cells it could actually help to understand what happening in your tableview a bit faster. But I think it is the discussable moment. Guys from my team currently prefer more informative variant.

But I will try to push forward the improvement.

**Comment by maxsokolov** [comment]
Glad to inform that I've got an approval from my team. After some discussion we've decided that this is actually good change that makes this library even better.

I also have to thank the community which pointed attention on this change several times.

**Comment by maxsokolov** [comment]
So, new changes are also available via Cocoapods, version 2.0.0.
