### ISSUE TITLE
Поддержка нескольких действий одного типа

### ISSUE THREAD

**Issue by noxt** [maxsokolov/TableKit#53]
@maxsokolov Привет! Спасибо за либу)

Расскажи, это так задумано, что если добавлять два действия одного типа, то выполняется только последний?

Мы просто написали экстеншн к `TableRowAction` с дефолтными методами по кастомизации и вызываем это таким образом:
`TableRow<TaskClientInfoCell>(item: task, actions: [.hideSeparatorAction(), .disableSelectionAction()])`
но, как я уже описал выше, выполняется только последний экшн.

Я сейчас в форке сделаю поддержку нескольких экшенов одного типа, нужно потом PR делать или вам такое не надо?

**Comment by maxsokolov** [comment]
@noxt привет!

>Расскажи, это так задумано, что если добавлять два действия одного типа, то выполняется только последний?
Каждый action сейчас хранится по ключу от имени действия, поэтому каждый новый action просто перезаписывает предыдущий по этому же ключу.

Это хорошая идея. Мы тоже замечали, что такой функционал неплохо бы иметь, но тут есть несколько концептуальных вопросов:

1) Должно ли несколько действий описываться разными объектами `TableRowAction<StringTableViewCell>(.click)`? 
2) Или это должен быть один объект `TableRowAction` но с методами вроде `addHandler`. Это может быть логичным, у меня один .click и несколько handlers к нему...

Также, что делать в случае, если я хочу удалить одно из действий. И нужно ли вообще давать возможность удалить действие. 

В случае с первым подходом - удаление можно было бы сделать назначив `TableRowAction` какой-то id и добавить для `Row` метод `removeActionForId`. Со вторым подходом не так просто... `addHandlerForKey`

Функция полезная, но видение реализации еще не устоялось.

**Comment by maxsokolov** [comment]
@noxt версия 2.1 теперь поддерживает несколько действий одного типа. Обновил доку.
