### ISSUE TITLE
ConfigureCell не сохраняется значение

### ISSUE THREAD

**Issue by Banck** [maxsokolov/TableKit#63]
Привет! Используя демо проект заменил UILabel на UITextField в NibTableViewCell и в NibTableViewCell.swift сделал так:
   ```
 func configure(with number: Int) {
       
    }
```
Сделал 20 ячеек. В первой ячейке ввожу текст в UITextField и скролю - в новых ячейках появляется такой же текст.
Да, понятно, что используется reusable cell,  но подскажите, пожалуйста, best way чтобы "сохранялись ячейки" используя TableKit?

**Comment by maxsokolov** [comment]
Привет!

Т.к. ячейки переиспользуются, то после изменения значения в textField его нужно где-то сохранить. Для это можно подписаться на эвенты от UITextField:
`
func textFieldValueChanged(textField: UITextField) {
    TableCellAction(key: "MyAction", sender: self).invoke()
}
`
Поймать этот эвент в TableRow:
`
TableRow<NibTableViewCell>(item: $0)
    .on("MyAction") { (_) -> Void in
        // тут сохраняем значение cell.textField.text        
    }
    .on(.configure) { (_) -> Void in
        // тут снова ставим
    }
`
