### ISSUE TITLE
[Question] [macOS] Any recommendations?

### ISSUE THREAD

**Issue by astrokin** [maxsokolov/TableKit#66]
@maxsokolov you did a really great job. i've successfully used TableKit in more then 5 last projects. But currently i've an iOS project needed to be ported to macOS version. What would you recommend, some analogue of TableKit for macOS?

**Comment by maxsokolov** [comment]
@astrokin hi!
> you did a really great job. i've successfully used TableKit in more then 5 last projects
I'm really glad to hear that! High five!)

About your question - to be honest, I don't have any experience of writing macOS apps, so unfortunately I don't have any recommendations here...

**Comment by astrokin** [comment]
Thank you very much for quick response! May be will update this thread with final solution.
