### ISSUE TITLE
UICollectionView support

### ISSUE THREAD

**Issue by yakubbaev** [maxsokolov/TableKit#67]
Thank you for great library!

BTW, is there any plans on expanding to UICollectionView?

**Comment by maxsokolov** [comment]
@yakubbaev hi! Thanks!

I don't have any plans to support UICollectionView. 
Take a look at [IGListKit](https://github.com/Instagram/IGListKit) or [DTCollectionViewManager](https://github.com/DenHeadless/DTCollectionViewManager).
