### ISSUE TITLE
Plain table with no header or footer still shows the header/footer

### ISSUE THREAD

**Issue by danmartyn** [maxsokolov/TableKit#71]
If I initialize a new section, using either of the constructors that take a header/footer string or view and pass nil for both, when I run, the table still shows empty header/footer views, instead of not showing them. For now, I end up needing to set the footer height to CGFloat.leastNormalMagnitude to make them go away. Can this be done in the framework for us?

**Comment by maxsokolov** [comment]
@danmartyn 

I'm afraid you are ending up with the right solution for now.

**Comment by danmartyn** [comment]
Ok, I can stick with that for now then, just wanted to make sure I wasn't doing something wrong. Thanks.
