### ISSUE TITLE
[QUESTION] Scrolling is relatively glitchy

### ISSUE THREAD

**Issue by Avighnash** [maxsokolov/TableKit#72]
I noticed that while scrolling through a UIView with a lot of cells, the line seperators flicker and it doesn't look to smooth. Would it be possible to make scrolling smoother?

**Comment by maxsokolov** [comment]
@Avighnash hello!

So let's find out the cause. Do you have a difficult layout in your cells (may be complex autolayout)? If so, I suggest to simplify it and perform some tests to see if it affects scrolling.

You could check an example project, increase an amount of cells there and see that it works pretty well.

**Comment by Avighnash** [comment]
The cells have an extremely simple layout, just a text label. Another quick question, what is the advantage of using TableSections over just using rows? When I first saw that I thought it would be be one of those header cells that can be found in the settings app which groups a bunch of cells.

**Comment by maxsokolov** [comment]
> The cells have an extremely simple layout

Can you reproduce this issue in this [demo](https://github.com/maxsokolov/TableKit/tree/master/Demo ) project? If you are not, can you attach your simple demo with issue here? In your case It's difficult to help without seeing any code.

> what is the advantage of using TableSections over just using rows

It's not the advantage, table view contains sections which contains rows (you can't have table views without sections, there are always at least one section). Sections can have headers and footers additionally (as you can see in the settings app). But you can add rows to `TableDirector` directly, it automatically creates a section for you.

**Comment by Avighnash** [comment]
I just tested it on my iPhone 6s, it seems to be an issue with the simulator that I used, not on the phone.
