### ISSUE TITLE
Support for moving rows?

### ISSUE THREAD

**Issue by mrojas** [maxsokolov/TableKit#76]
I see that the methods in the delegate to move rows are not implemented, and there is no associated action, thus getting:
```
NSInvalidArgumentException', reason: '-[TableKit.TableDirector tableView:moveRowAtIndexPath:toIndexPath:]: unrecognized selector sent to instance 0x6040000d7ae0
```

Am I missing something, or is not yet implemented? I can do it if needed.

Cheers

**Comment by maxsokolov** [comment]
Hey @mrojas 

Sorry for late response. You are not missing anything. That kind of feature is not supported by TableKit.

**Comment by mrojas** [comment]
#77
