### ISSUE TITLE
Crash when doing clear()

### ISSUE THREAD

**Issue by bassebaba** [maxsokolov/TableKit#78]
I get a crash when i do:

```
tableDirector.clear()
tableDirector.refresh() 
```

It tries to do an invoke of "didEndDisplaying" but the sections/data is gone.

How do I clear the data in the correct way?

**Comment by maxsokolov** [comment]
Hey @bassebaba 

Fix https://github.com/maxsokolov/TableKit/pull/79
Check out 2.6.0 verstion

**Comment by bassebaba** [comment]
@maxsokolov works great now, thanks for the fast fix!
