### ISSUE TITLE
[ВОПРОС] Как перезагружать секции при постраничной загрузке

### ISSUE THREAD

**Issue by tmbiOS** [maxsokolov/TableKit#82]
Привет, Макс! Спасибо за твою работу.
Подскажи, как сделать перезагрузки секций при постраничной загрузке.
Когда делаю:
`tableDirector.clear()`
.... add section
.... add rows
```
tableDirector += section
tableDirector.reload()
```

То таблица скроллится в начало.

**Comment by maxsokolov** [comment]
@tmbiOS привет!

Тут нужно воспользоваться возможностями `UITableView`, вместо метода reload у `TableDirector`.
После того, как мы добавили данные (clear делать не нужно):
```
tableDirector += section
```
Нужно вручную вставить их в таблицу:
```
tableView.beginUpdates()
tableView.insertRows(at: [indexPath, indexPath, indexPath], with: .fade)
tableView.endUpdates()
```
Нужно только рассчитать правильные index path'ы.

**Comment by tmbiOS** [comment]
@maxsokolov Еще один вопрос, связан с предущим.
Если у меня сначала формируется таблица во viewDidLoad. 
Потом в какой-то ячейке происходит замена данных. А при скроллинге все обратно возвращается в начальное значение. Как это исправить?

**Comment by maxsokolov** [comment]
@tmbiOS привет! Прошу прощения за поздний ответ (был на каникулах). Если еще актуально. Видимо проблема в том, что модель представления не соответсвует модели данных.

Не достаточно просто использовать tableView.insertRows, нужно данные также обновить и в tableDirector в нужных секциях.
