### ISSUE TITLE
Can't remove top extra space for grouped tableview

### ISSUE THREAD

**Issue by SergeMaslyakov** [maxsokolov/TableKit#84]
Hi.

I have faced for strange behaviour of grouped tableview with `TableKit`.
I can't remove extra top space for grouped table (I use `xibs` - iOS 10/11).

I do following:

```
    func reload(withModels models: [MyModel]) {

        tableDirector.clear()

        let section = TableSection()
        tableDirector += section

        section.headerHeight = CGFloat.leastNormalMagnitude
        section.footerHeight = CGFloat.leastNormalMagnitude

        for item in models {

            section += TableRow<MyTableViewCell>(item: item)
                    .on(.click, handler: { [weak viewOutput] _ in

                    })
        }

        tableDirector.reload()
    }
```

Also I have tried to make subclass of `TableDirector` and always return `CGFloat.leastNormalMagnitude` for all sections. It's didn't work also.

--- But ----
If I implement datasource/delegate manually. It works fine - no any extra space on top.

```

extension MyTableDataSource: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return MyTableViewCell.defaultHeight
    }

    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return CGFloat.leastNormalMagnitude
    }

    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return CGFloat.leastNormalMagnitude
    }
}

```

**Comment by maxsokolov** [comment]
Hey @SergeMaslyakov 

I've tried to reproduce the issue in the demo app from the repo. What I've done:
1) Set group style from table view in a storyboard for main controller. Right after that I can see extra space on top.
2) Then in `MainController` added a section and set:
```
section.headerHeight = CGFloat.leastNormalMagnitude
```
Extra space disappeared.

Further steps:

1) Could you provide a demo app with the issue?
2) Or try to create a section in the following way:
```
TableSection(headerView: UIView(frame: CGRect(x: 0, y: 0, width: 0, height: CGFloat.leastNormalMagnitude)), footerView: nil)
```

**Comment by SergeMaslyakov** [comment]
@maxsokolov, thanks for answer. I want to note that I use xib instead storyboards.

Anyway, I have done bit demo.
See this repo [demo repo](https://github.com/SergeMaslyakov/GithubClient/tree/table-kit)

For `GithubClient/src/modules/GistsBrowser/View/GistsBrowserViewController` is implemented two datasources. `TableKitGistsBrowserTableDataSource` uses `TableKit` and other one `BaseGistsBrowserTableDataSource` manages table stuff itself. 

You can switch them by uncommenting in the `GistsBrowserViewController `.

**Comment by maxsokolov** [comment]
@SergeMaslyakov alright, thanks for the demo!

I've started investigation. Here is what I've done in `TableKitGistsBrowserTableDataSource`:
```
let section = TableSection()
let sectionHeader = UIView(frame: CGRect(x: 0, y: 0, width: 150, height: 300))
sectionHeader.backgroundColor = UIColor.red
section.headerView = sectionHeader
tableDirector += section

//section.headerHeight = CGFloat.leastNormalMagnitude
//section.footerHeight = CGFloat.leastNormalMagnitude
```
<img width="482" alt="screen shot 2018-06-15 at 00 44 39" src="https://user-images.githubusercontent.com/757071/41439916-52b0cb60-7035-11e8-82f8-f136f747d181.png">

Still a gap.. pff.. nice.
And then:
```
tableView.tableFooterView = nil
tableView.tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: 150, height: CGFloat.leastNormalMagnitude))
```
Result:
<img width="489" alt="screen shot 2018-06-15 at 00 46 56" src="https://user-images.githubusercontent.com/757071/41440027-a549877c-7035-11e8-8ecc-e0092e2d8905.png">

I don't know any better solution for now.

**Comment by SergeMaslyakov** [comment]
@maxsokolov 

Thanks for help and workaround.
I think it's related to `xib's`, bcoz this isn't reproduced when I use a storyboard.

**Comment by SergeMaslyakov** [comment]
@maxsokolov 

Hi again. I have found some interesting thing.

This problem appears when I use `lazy var` for  `TableDirector`

```
    private lazy var tableDirector: TableDirector = {
        return TableDirector(tableView: tableView)
    }()
```

When I declare it as a simple `var` the problem disappears.

```
    private var tableDirector: TableDirector

```

**Comment by hastlerr** [comment]
```
override func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
    return CGFloat.leastNormalMagnitude
}
```

**Comment by kiishanbarmawala** [comment]
> @SergeMaslyakov alright, thanks for the demo!
> 
> I've started investigation. Here is what I've done in `TableKitGistsBrowserTableDataSource`:
> 
> ```
> let section = TableSection()
> let sectionHeader = UIView(frame: CGRect(x: 0, y: 0, width: 150, height: 300))
> sectionHeader.backgroundColor = UIColor.red
> section.headerView = sectionHeader
> tableDirector += section
> 
> //section.headerHeight = CGFloat.leastNormalMagnitude
> //section.footerHeight = CGFloat.leastNormalMagnitude
> ```
> 
> <img alt="screen shot 2018-06-15 at 00 44 39" width="482" src="https://user-images.githubusercontent.com/757071/41439916-52b0cb60-7035-11e8-82f8-f136f747d181.png">
> 
> Still a gap.. pff.. nice.
> And then:
> 
> ```
> tableView.tableFooterView = nil
> tableView.tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: 150, height: CGFloat.leastNormalMagnitude))
> ```
> 
> Result:
> <img alt="screen shot 2018-06-15 at 00 46 56" width="489" src="https://user-images.githubusercontent.com/757071/41440027-a549877c-7035-11e8-8ecc-e0092e2d8905.png">
> 
> I don't know any better solution for now.

It's also working for me... Thanks... you saved my day!

**Comment by AKGupta31** [comment]
If you are using header view also then you just need to do the following..

func tableView(_ tableView: UITableView, estimatedHeightForHeaderInSection section: Int) -> CGFloat {
        return CGFloat.leastNormalMagnitude
}

It worked for me
