### ISSUE TITLE
ConfigurableCell T triggers SwiftLint warning

### ISSUE THREAD

**Issue by kean** [maxsokolov/TableKit#85]
Hey, @maxsokolov!

We have a minor issue with `ConfigurableCell`. Every time we implement `ConfigurableCell` and provide a typealias for `T` it triggers a SwiftLint warning based on [`type_name`](https://github.com/realm/SwiftLint/blob/master/Rules.md#type-name) rule (which is enabled by default in SwiftLint):

```
../CustomTableCell.swift:13:15: warning: Type Name Violation: Type name should be between 3 and 60 characters long: 'T' (type_name)
```

https://github.com/maxsokolov/TableKit/blob/dd8e5d0625b0775e77d7c3464f542e9acb8e16ed/Sources/ConfigurableCell.swift#L25

As a workaround we disable this warning every time we implement `ConfigurableCell` protocol. It would be nice to rename `T` into something more meaningful like `TableDisplayData` or something similar to prevent this warning form being triggered by SwiftLint.

**Comment by maxsokolov** [comment]
Hey @kean 

This is really nice to have a meaningful name for this associatedtype. I have updated master and pushed new version [v2.7.0](https://github.com/maxsokolov/TableKit/releases/tag/2.7.0) to Cocoapods.

Thank you for pointing that out.

**Comment by kean** [comment]
Thanks!
