### ISSUE TITLE
Remove/delete a section

### ISSUE THREAD

**Issue by SoriUR** [maxsokolov/TableKit#90]
Hello, there
I think i've faced some strange(at least as for me) behavior managing sections.
"Insert", "append", "replace" work perfectly, but "remove" and "delete" are different.
It seems like user has to call "tableDirector.reload()" explicitly after calling "remove" or "delete" otherwise no changes are applied to the table.
I find it uncleare, that only these to functions require explicit reload, and unfortunatly no desctiption is attached to functions for clarification.

**Comment by maxsokolov** [comment]
Hey @SoriUR 

I have to admit, it's unclear with current documentation. If you delete sections/rows you also have to delete them from tableview itself:
```
tableDirector.delete(sectionAt: 0)
tableView.beginUpdates()
tableView.deleteSections(/*...*/)
tableView.endUpdates() 
```
`tableView.reloadData()` also works.
