### ISSUE TITLE
How to reload a concrete row or cell?

### ISSUE THREAD

**Issue by GDXRepo** [maxsokolov/TableKit#92]
How can I reload a concrete row or cell? If I try to enumerate sections and rows inside them, then I'm unable to perform type casting ("Row" class has no useful data, but casting to "TableRow" is impossible due to its generic parameter). Also from the "Row" I can't access its data to read or modify it. Replacing the row with the new TableRow and reconfiguring it is very inconvenient and inappropriate for me.

**Comment by maxsokolov** [comment]
Hey @GDXRepo 

You could keep a ref to a row somewhere
```
let row = TableRow<ConfigurableTableViewCell>(item: "Data", actions: [])
```

and then access it's item that you want to modify

```
row.item
```

then, if it's easy to calculate an `indexPath` you can easily call UITableView for [update](https://developer.apple.com/documentation/uikit/uitableview/1614935-reloadrows) at `indexPath`.

**Comment by GDXRepo** [comment]
Hmm. Thank you, I'll try it.
